baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "Hugo実験ぺーじ"

hasCJKLanguage = true

DefaultContentLanguage = "ja"

[params]
  description = "An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project."
  keywords = "index,Hugo,実験,キーワード"
